### ISSUE TITLE
Rework the Model

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bord__backend#8]
Run SQLite in memory. 

1) Make Controller ask Model 1 for markdown-files for one theme.   
2) Give data to View and convert md to JSON.    
3) Let Model 2 store JSON in SQL 
4) When request comes via API, ask Model 2 for JSON and return it to the API

**Comment by pontalainen** [comment]
Now I import and export functions everywhere. No I´m kidding, not everywhere. Router.js now imports one function each from model and views.

The function imported from model, "fetchContent" fetches data from the database, and is called on get requests with and **id**, for example "localhost:8080/**fruit**".

The function imported from views, "converter" fetches the the markdown files (at the moment from a local directory), converts them into JSON and stores them in the database (at the moment only a manually specified table). This function in called on get requests without any id (the home page), and they might be for example "localhost:8080".
